### ISSUE TITLE
Doesn't appear to work in Godot 4.3 .net

### ISSUE THREAD

**Issue by symbol24** [raiyni/miniscript-cs#1]
when attempting to install the plugin through the assetlib, there seems to be a resource file that is broken.

When attempting to turn the plugin on in the project settings, Godot turns it off.

https://i.imgur.com/sgQyUR5.png

https://i.imgur.com/GHw5dqv.png

**Comment by Aedda** [comment]
Having the same issue.

**Comment by Aedda** [comment]
I added a blank C# script to a node then built my project which caused the MiniScript scripts to compile, after this I was able to enable the plugin. I'm reasonably sure just running the scene and then enabling the plugin would probably work. Good luck!

Note I have not actually tested that the plugin works, just that the error is gone, cheers!

**Comment by symbol24** [comment]
I also can bypass the error, will test the plugin next

**Comment by raiyni** [comment]
Sorry, I missed the original email. I'll look, I originally wrote this on 4.3-dev so I'm kind of surprised if this is the case.

**Comment by raiyni** [comment]
This appears to be an issue with the IDE not automatically compiling C# based addons when you install them unfortunately. You don't need to make a blank script to use it, you just need to hit the build project button after anytime you install a c# addon.
